version: '3'

services:

  # RabbitMQ
  queue:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: privneg
      RABBITMQ_DEFAULT_PASS: privneg
    ports:
      - "8080:15672"

  # PostgresSQL
  db:
    image: postgres
    environment:
      POSTGRES_USER: privneg
      POSTGRES_PASSWORD: privneg
      POSTGRES_DB: privneg

  # Redis
  cache:
    image: redis

  # Golang API
  api:
    build:
      context: ./backend/
      dockerfile: dev.Dockerfile
    command: fresh
    volumes:
      - "./backend:/go/src/github.com/VJftw/privacy-negotiator/backend/"
    working_dir: /go/src/github.com/VJftw/privacy-negotiator/backend/priv-neg
    environment:
      TYPE: API
      JWT_SECRET: development
      RABBITMQ_HOSTNAME: rabbit
      RABBITMQ_USER: privneg
      RABBITMQ_PASS: privneg
      REDIS_HOST: redis
      PORT: 80
    ports:
      - "80:80"
    depends_on:
      - queue
      - cache
    links:
      - "queue:rabbit"
      - "cache:redis"

  # Golang Worker - Auth queue
  worker:
    build:
      context: ./backend/
      dockerfile: dev.Dockerfile
    command: fresh
    volumes:
      - "./backend:/go/src/github.com/VJftw/privacy-negotiator/backend/"
    working_dir: /go/src/github.com/VJftw/privacy-negotiator/backend/priv-neg
    environment:
      TYPE: WORKER
      QUEUE: auth-queue
      RABBITMQ_HOSTNAME: rabbit
      RABBITMQ_USER: privneg
      RABBITMQ_PASS: privneg
      POSTGRES_HOST: postgres
      POSTGRES_USER: privneg
      POSTGRES_DBNAME: privneg
      POSTGRES_PASSWORD: privneg
      REDIS_HOST: redis
      FACEBOOK_APP_ID: 431282593918092
      FACEBOOK_APP_SECRET: 5208ed76bd97a1f30533bda1478bc594
    depends_on:
      - queue
      - db
      - cache
    links:
      - "queue:rabbit"
      - "db:postgres"
      - "cache:redis"

  # Angular 4 Web App
  web:
    image: node:8
    command: node_modules/.bin/ng serve --host=0.0.0.0
    working_dir: /app
    volumes:
      - "./web_app/priv-neg:/app"
    ports:
      - "4200:4200"
