version: '3'

services:

  # RabbitMQ
  queue:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: privneg
      RABBITMQ_DEFAULT_PASS: privneg
    ports:
      - "8080:15672"

  # PostgresSQL
  db:
    image: postgres
    environment:
      POSTGRES_USER: privneg
      POSTGRES_PASSWORD: privneg
      POSTGRES_DB: privneg

  # Golang API
  api:
    build:
      context: ./api/
      dockerfile: dev.Dockerfile
    command: /bin/sh -c "glide install && fresh"
    volumes:
      - "./api:/go/src/github.com/VJftw/privacy-negotiator/api/"
    working_dir: /go/src/github.com/VJftw/privacy-negotiator/api/priv-neg
    environment:
      JWT_SECRET: development
      RABBITMQ_HOSTNAME: rabbit
      RABBITMQ_USER: privneg
      RABBITMQ_PASS: privneg
      PORT: 80
    ports:
      - "80:80"
    depends_on:
      - queue
    links:
      - "queue:rabbit"

  # Golang Worker
  worker:
    build:
      context: ./worker/
      dockerfile: dev.Dockerfile
    command: /bin/sh -c "glide install && fresh"
    volumes:
      - "./worker:/go/src/github.com/VJftw/privacy-negotiator/worker/"
    working_dir: /go/src/github.com/VJftw/privacy-negotiator/worker/priv-neg
    environment:
      RABBITMQ_HOSTNAME: rabbit
      RABBITMQ_USER: privneg
      RABBITMQ_PASS: privneg
      POSTGRES_HOST: postgres
      POSTGRES_USER: privneg
      POSTGRES_DBNAME: privneg
      POSTGRES_PASSWORD: privneg
      FACEBOOK_APP_ID: 431282593918092
      FACEBOOK_APP_SECRET: 5208ed76bd97a1f30533bda1478bc594
    depends_on:
      - queue
      - db
    links:
      - "queue:rabbit"
      - "db:postgres"

  # Angular 4 Web App
  web:
    image: node:8
    command: node_modules/.bin/ng serve --host=0.0.0.0
    working_dir: /app
    volumes:
      - "./web_app/priv-neg:/app"
    ports:
      - "4200:4200"
