version: '3'

services:

  # RabbitMQ
  queue:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: privneg
      RABBITMQ_DEFAULT_PASS: privneg
    ports:
      - "8080:15672"

  # PostgresSQL
  db:
    image: postgres
    environment:
      POSTGRES_USER: privneg
      POSTGRES_PASSWORD: privneg
      POSTGRES_DB: privneg
    ports:
      - "5432:5432"

  # Redis
  cache:
    image: redis
    ports:
      - "6379:6379"

  # Golang API
  api:
    build:
      context: ./backend/
      dockerfile: dev.Dockerfile
    command: fresh
    restart: unless-stopped
    volumes:
      - "./backend:/go/src/github.com/VJftw/privacy-negotiator/backend/"
    working_dir: /go/src/github.com/VJftw/privacy-negotiator/backend/priv-neg
    environment:
      TYPE: API
      JWT_SECRET: development
      RABBITMQ_HOSTNAME: rabbit
      RABBITMQ_USER: privneg
      RABBITMQ_PASS: privneg
      REDIS_HOST: redis
      PORT: 80
    ports:
      - "80:80"
    depends_on:
      - queue
      - cache
    links:
      - "queue:rabbit"
      - "cache:redis"

  # Golang Worker - Auth queue
  worker-auth-long-token:
    build:
      context: ./backend/
      dockerfile: dev.Dockerfile
    command: fresh
    restart: unless-stopped
    volumes:
      - "./backend:/go/src/github.com/VJftw/privacy-negotiator/backend/"
    working_dir: /go/src/github.com/VJftw/privacy-negotiator/backend/priv-neg
    environment:
      TYPE: WORKER
      QUEUE: auth-long-token
      RABBITMQ_HOSTNAME: rabbit
      RABBITMQ_USER: privneg
      RABBITMQ_PASS: privneg
      POSTGRES_HOST: postgres
      POSTGRES_USER: privneg
      POSTGRES_DBNAME: privneg
      POSTGRES_PASSWORD: privneg
      REDIS_HOST: redis
      FACEBOOK_APP_ID: 431282593918092
      FACEBOOK_APP_SECRET: 5208ed76bd97a1f30533bda1478bc594
    depends_on:
      - queue
      - db
      - cache
    links:
      - "queue:rabbit"
      - "db:postgres"
      - "cache:redis"

  worker-photo-tags:
    build:
      context: ./backend/
      dockerfile: dev.Dockerfile
    command: fresh
    restart: unless-stopped
    volumes:
      - "./backend:/go/src/github.com/VJftw/privacy-negotiator/backend/"
    working_dir: /go/src/github.com/VJftw/privacy-negotiator/backend/priv-neg
    environment:
      TYPE: WORKER
      QUEUE: photo-tags
      RABBITMQ_HOSTNAME: rabbit
      RABBITMQ_USER: privneg
      RABBITMQ_PASS: privneg
      POSTGRES_HOST: postgres
      POSTGRES_USER: privneg
      POSTGRES_DBNAME: privneg
      POSTGRES_PASSWORD: privneg
      REDIS_HOST: redis
      FACEBOOK_APP_ID: 431282593918092
      FACEBOOK_APP_SECRET: 5208ed76bd97a1f30533bda1478bc594
    depends_on:
      - queue
      - db
      - cache
    links:
      - "queue:rabbit"
      - "db:postgres"
      - "cache:redis"

  worker-community-detection:
      build:
        context: ./backend/
        dockerfile: dev.Dockerfile
      command: fresh
      restart: unless-stopped
      volumes:
        - "./backend:/go/src/github.com/VJftw/privacy-negotiator/backend/"
      working_dir: /go/src/github.com/VJftw/privacy-negotiator/backend/priv-neg
      environment:
        TYPE: WORKER
        QUEUE: community-detection
        RABBITMQ_HOSTNAME: rabbit
        RABBITMQ_USER: privneg
        RABBITMQ_PASS: privneg
        POSTGRES_HOST: postgres
        POSTGRES_USER: privneg
        POSTGRES_DBNAME: privneg
        POSTGRES_PASSWORD: privneg
        REDIS_HOST: redis
        FACEBOOK_APP_ID: 431282593918092
        FACEBOOK_APP_SECRET: 5208ed76bd97a1f30533bda1478bc594
      depends_on:
        - queue
        - db
        - cache
      links:
        - "queue:rabbit"
        - "db:postgres"
        - "cache:redis"

  worker-persist-category:
    build:
      context: ./backend/
      dockerfile: dev.Dockerfile
    command: fresh
    restart: unless-stopped
    volumes:
      - "./backend:/go/src/github.com/VJftw/privacy-negotiator/backend/"
    working_dir: /go/src/github.com/VJftw/privacy-negotiator/backend/priv-neg
    environment:
      TYPE: WORKER
      QUEUE: persist-category
      RABBITMQ_HOSTNAME: rabbit
      RABBITMQ_USER: privneg
      RABBITMQ_PASS: privneg
      POSTGRES_HOST: postgres
      POSTGRES_USER: privneg
      POSTGRES_DBNAME: privneg
      POSTGRES_PASSWORD: privneg
      REDIS_HOST: redis
      FACEBOOK_APP_ID: 431282593918092
      FACEBOOK_APP_SECRET: 5208ed76bd97a1f30533bda1478bc594
    depends_on:
      - queue
      - db
      - cache
    links:
      - "queue:rabbit"
      - "db:postgres"
      - "cache:redis"

  worker-persist-user-clique:
    build:
      context: ./backend/
      dockerfile: dev.Dockerfile
    command: fresh
    restart: unless-stopped
    volumes:
      - "./backend:/go/src/github.com/VJftw/privacy-negotiator/backend/"
    working_dir: /go/src/github.com/VJftw/privacy-negotiator/backend/priv-neg
    environment:
      TYPE: WORKER
      QUEUE: persist-user-clique
      RABBITMQ_HOSTNAME: rabbit
      RABBITMQ_USER: privneg
      RABBITMQ_PASS: privneg
      POSTGRES_HOST: postgres
      POSTGRES_USER: privneg
      POSTGRES_DBNAME: privneg
      POSTGRES_PASSWORD: privneg
      REDIS_HOST: redis
      FACEBOOK_APP_ID: 431282593918092
      FACEBOOK_APP_SECRET: 5208ed76bd97a1f30533bda1478bc594
    depends_on:
      - queue
      - db
      - cache
    links:
      - "queue:rabbit"
      - "db:postgres"
      - "cache:redis"

  worker-persist-photo:
    build:
      context: ./backend/
      dockerfile: dev.Dockerfile
    command: fresh
    restart: unless-stopped
    volumes:
      - "./backend:/go/src/github.com/VJftw/privacy-negotiator/backend/"
    working_dir: /go/src/github.com/VJftw/privacy-negotiator/backend/priv-neg
    environment:
      TYPE: WORKER
      QUEUE: persist-photo
      RABBITMQ_HOSTNAME: rabbit
      RABBITMQ_USER: privneg
      RABBITMQ_PASS: privneg
      POSTGRES_HOST: postgres
      POSTGRES_USER: privneg
      POSTGRES_DBNAME: privneg
      POSTGRES_PASSWORD: privneg
      REDIS_HOST: redis
      FACEBOOK_APP_ID: 431282593918092
      FACEBOOK_APP_SECRET: 5208ed76bd97a1f30533bda1478bc594
    depends_on:
      - queue
      - db
      - cache
    links:
      - "queue:rabbit"
      - "db:postgres"
      - "cache:redis"

  worker-conflict-detection-and-resolution:
    build:
      context: ./backend/
      dockerfile: dev.Dockerfile
    command: fresh
    restart: unless-stopped
    volumes:
      - "./backend:/go/src/github.com/VJftw/privacy-negotiator/backend/"
    working_dir: /go/src/github.com/VJftw/privacy-negotiator/backend/priv-neg
    environment:
      TYPE: WORKER
      QUEUE: conflict-detection-and-resolution
      RABBITMQ_HOSTNAME: rabbit
      RABBITMQ_USER: privneg
      RABBITMQ_PASS: privneg
      POSTGRES_HOST: postgres
      POSTGRES_USER: privneg
      POSTGRES_DBNAME: privneg
      POSTGRES_PASSWORD: privneg
      REDIS_HOST: redis
      FACEBOOK_APP_ID: 431282593918092
      FACEBOOK_APP_SECRET: 5208ed76bd97a1f30533bda1478bc594
    depends_on:
      - queue
      - db
      - cache
    links:
      - "queue:rabbit"
      - "db:postgres"
      - "cache:redis"

  # Angular 4 Web App
  # web:
  #   image: node:8
  #   command: node_modules/.bin/ng serve --host=0.0.0.0 --disable-host-check
  #   working_dir: /app
  #   volumes:
  #     - "./web_app/priv-neg:/app"
  #   ports:
  #     - "4200:4200"
