version: '3'

services:
  queue:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: privneg
      RABBITMQ_DEFAULT_PASS: privneg
    ports:
      - "8080:15672"
  api:
    build:
      context: .
      dockerfile: dev.Dockerfile
    command: fresh
    volumes:
      - ".:/go/src/github.com/VJftw/privacy-negotiator/api/"
    working_dir: /go/src/github.com/VJftw/privacy-negotiator/api/priv-neg
    environment:
      JWT_SECRET: development
      RABBITMQ_HOSTNAME: rabbit
      RABBITMQ_USER: privneg
      RABBITMQ_PASS: privneg
      PORT: 80
    ports:
      - "80:80"
    depends_on:
      - queue
    links:
      - "queue:rabbit"
